packadd! dracula
syntax enable
let g:dracula_italic = 0
let g:dracula_colorterm = 0
colorscheme dracula
set noswapfile
set nu rnu
set hlsearch
set ignorecase
set incsearch
set tabstop=4
set shiftwidth=4
set expandtab
set shiftwidth=4
